-- Write a query to retrieve the names of all customers who have placed orders, sorted in alphabetical order

SELECT DISTINCT cust.CustomerName FROM Customers cust
INNER JOIN Orders ord ON ord.CustomerID = cust.CustomerID
ORDER BY cust.CustomerName ASC;

-- Write a query to retrieve the total revenue generated by each product, based on the quantity sold and the unit price. 
SELECT prod.ProductID, prod.ProductName, SUM(ordet.Quantity * prod.Price) as "Revenue" FROM OrderDetails ordet
INNER JOIN Products prod ON prod.ProductID = ordet.ProductID
GROUP BY prod.ProductID, prod.ProductName

-- Write a query to retrieve the names of all customers who have not placed any orders, sorted by country and then by city 
SELECT DISTINCT cust.CustomerName, cust.Country, cust.City FROM Customers cust
LEFT JOIN Orders ord ON ord.CustomerID = cust.CustomerID
WHERE ord.CustomerID IS NULL
ORDER BY cust.Country, cust.City

SELECT DISTINCT cust.CustomerName, cust.Country, cust.City FROM Customers cust
WHERE cust.CustomerID NOT IN (SELECT DISTINCT ord.CustomerID FROM Orders ord)
ORDER BY cust.Country, cust.City

-- Write a query to retrieve the top 5 best-selling products, based on the total quantity sold across all orders
SELECT TOP 5 prod.ProductID, prod.ProductName, SUM(ordet.Quantity) FROM OrderDetails ordet
INNER JOIN Products prod ON prod.ProductID = ordet.ProductID
GROUP BY prod.ProductID, prod.ProductName
ORDER BY SUM(ordet.Quantity) DESC


